feat: adds scrollSize for batch and enqueue tasks
ICIJ/datashare pull request #1349
Opened 2024-02-28 14:34 UTC by mvanzalu

Related to [this issue](https://github.com/ICIJ/datashare/issues/1270)

This PR aims to add the scroll size option for Batch Search/Download and EnqueueTask.
It also define more default constants values options.

Scroll slice option for the other tasks can be issued in another story as the implementation is very specific for each tasks (we can also dig into the using of elasticsearch's [PIT](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/point-in-time-api.html#point-in-time-keep-alive)

2024-02-28 15:22 UTC, pirhoo requested changes
This looks good but it's not retro-compatible (CLI using the existing `scrollSize` will be ignored). Instead we could use the scrollSize value as default value in BatchSearchRunner and BatchDownloadRunner.

2024-02-28 17:38 UTC, mvanzalu commented
> This looks good but it's not retro-compatible (CLI using the existing `scrollSize` will be ignored). Instead we could use the scrollSize value as default value in BatchSearchRunner and BatchDownloadRunner.

Alright and having `batchSearchScrollSize`in the params would override the `scrollSize` parameter for example ?

2024-02-28 17:45 UTC, pirhoo commented
Exactly!

2024-02-29 09:34 UTC, pirhoo approved these changes

2024-02-29 09:48 UTC, merged